### ISSUE TITLE
References to external documents?

### ISSUE THREAD

**Issue by lclevy** [geraldholdsworth/DiscImageManager#18]
Maybe your work is based on previous people work, why not citing them?

**Comment by lclevy** [comment]
I see no references in your pdf about file formats.

**Comment by geraldholdsworth** [comment]
Hi Laurent,

 

I’m sorry, you’ve lost me.

Both the Guide to File Formats PDF and the User Guide both cite references from where I got my information, including your Amiga ADF documentation.

The Guide to File Formats PDF is a couple of years out of date, and I haven’t yet cited the Microsoft document I referenced in the User Guide.

 

From: Laurent Clévy ***@***.***>
Reply to: geraldholdsworth/DiscImageManager ***@***.***>
Date: Friday, 29 April 2022 at 18:46
To: geraldholdsworth/DiscImageManager ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [geraldholdsworth/DiscImageManager] References to external documents? (Issue #18)

 

I see no references in your pdf about file formats.

**Comment by lclevy** [comment]
Sorry Gerald, it is in **acknowledgments** section, I'm sorry I missed that. 
It is nice you document old filesystems !
I visited scotland in 2019 and loved Skye Island and Edinburg ! will return !
