### ISSUE TITLE
Generated ADFS D images don't work in Arthur

### ISSUE THREAD

**Issue by egrath** [geraldholdsworth/DiscImageManager#34]
**Problem**:

When generating ADFS D images, they don't work on Arthur 1.20 and always result in "BROKEN DIRECTORY". Opening a disk image formatted in Arthur works however (but as soon as you save it, "BROKEN DIRECTORY" again)

**Expected result**:

ADFS D images work in Arthur too

**Workaround**:

None discovered yet

**Comment by geraldholdsworth** [comment]
Thank you for letting me know.
I, currently, have no way of testing this out as I don't have access to an emulator running Arthur. However, I will investigate and see if I can persuade something to work.

**Comment by geraldholdsworth** [comment]
Quick question - if you open a disc image, which has been formatted and saved in Arthur, in Disc Image Manager, then immediately save it, does it still open in Arthur?

**Comment by egrath** [comment]
If you just open it in DiscImageManager and save it without doing anything else, then the image still works. I did more tests with a image formatted in Arthur and modified in DiscImageManager:

Changing the title of the disc: works
Creating a single directory on the disc: directory visible but changing to that directory results in "BROKEN DIRECTORY"
Adding a single file on the disc to $: works

So it seems that directories are the problem. For comparison, i attached a archive with two ADFS D images:

oneDirArthur: Formatted in Arthur, directory created in Arthur with `*CDIR TEST`
oneDirDIM: Formatted in Arthur, directory created in DIM and renamed to 'TEST'

[disks.zip](https://github.com/user-attachments/files/16685996/disks.zip)

**Comment by geraldholdsworth** [comment]
Sorry for the delay - I haven't forgotten about this. Just been busy with work and home.
The only differences I can see between the two images are the repeat of the catalogue at the end of the directory structure. This doesn't bother other versions of ADFS, so it could simply be that Arthur is bothered.

**Comment by geraldholdsworth** [comment]
It seems that Arthur ADFS is rather fussy about different directories on the same disc having different directory IDs. DIM was mixing "Hugo" directories with "Nick" directories (the four byte sequence to identify a directory on an ADFS disc).
RISC OS Filecore isn't so fussy.
I'll get a new, interim, version compiled and uploaded over the coming few days.
Incidentally, I found a marvelous resource to emulate Arthur and RISC OS in a web page:
https://archi.medes.live

**Comment by geraldholdsworth** [comment]
1.47.1 is now available, which addresses this bug.
